apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpechart.fullname" . }}
  labels:
    {{- include "cpechart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
      name: http
  selector:
    {{- include "cpechart.selectorLabels" . | nindent 4 }}
